[package]
name = "shared-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }