[build]
filehash = false
minify = "on_release"

[watch]
ignore = ["audio-worklet/pkg", "build"]

# Proxy configuration for development log server
[[proxies]]
backend = "http://127.0.0.1:3001/logs"
rewrite = "/logs"

# Build hooks
[[hooks]]
stage = "pre_build"
command = "./build-audio-worklet.sh"

[[hooks]]
stage = "pre_build"
command = "./generate-config.sh"
