[build]
filehash = false
minify = "on_release"

[watch]
ignore = ["audio-worklet/pkg"]

# Proxy configuration for development log server
[[proxies]]
backend = "http://127.0.0.1:3001/logs"
rewrite = "/logs"
