[package]
name = "audio-worklet"
version = "0.0.1"
authors = ["Joel Nises <joel.nises@gmail.com>"]
edition = "2024"
rust-version = "1.87"

[dependencies]
wmidi = "4.0.10"
crossbeam = "0.8.4"
wasm-bindgen = "0.2.100"
console_error_panic_hook = "0.1.7"
