# No default target - everything builds for native by default
# Use the aliases below for WASM development

[alias]
# WASM development aliases
check-wasm = "check --target wasm32-unknown-unknown"
clippy-wasm = "clippy --target wasm32-unknown-unknown"

# Development environment alias
xtask = "run -p xtask --"
