[package]
name = "dissonance-audio-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wmidi = "4.0.10"
crossbeam = "0.8.4"
dissonance-audio-types = { path = "../audio-types" }

# For WASM builds
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3"
